version: '3'

services:
  app:
    image: go-app:0.1
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
       SERVER_PORT: 8080
       MONGO_URL: mongodb://db:27017
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"