apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: golange
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: 465407669327.dkr.ecr.us-east-2.amazonaws.com/golange:latest
        ports:
          - containerPort: 8080
        env:
            - name: MONGO_URI
              value: "mongodb://mongo-app-service.go-survey.svc:27017"
            - name: APP_PORT
              value: "8080"


---

kind: Service
apiVersion: v1
metadata:
  name:  go-app
  namespace: golange
spec:
  selector:
    app:  go-app
  type:  ClusterIP
  ports:
  - name:  go-app
    port:  8080
    targetPort:  8080
  
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resou

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  namespace: golange
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: asion.great-site.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-app
            port:
              number: 8080