apiVersion: apps/v1
kind: Deployment
metadata:
  name:  db-deploy
  namespace: golange
  labels:
    app:  db-deploy
spec:
  selector:
    matchLabels:
      app: db-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app:  db-deploy
    spec:
      containers:
      - name:  db-deploy
        image:  mongo:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  27017
          name:  db-deploy
        volumeMounts:
        - name: mongodata
          mountPath: /data/db
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongo-pvc 


---
kind: Service
apiVersion: v1
metadata:
  name:  mogo-app-service
  namespace: golange
  labels:
    app: mongo-app
spec:
  selector:
    app:  db-deploy
  type:  ClusterIP 
  ports:
  - name:  mongo-app
    port:  27017
    targetPort:  27017

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: golange
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi