name: Actions Demo

on:
 push:
    branches:
      - '**'
 pull_request:
    branches:
      - '**'

jobs:
 echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo action step
        id: step_id
        run: echo "A new job with this id is added."
      - name: Print echo output
        run: echo "The output of the echo step was: ${{ steps.step_id.outputs.stdout }}"
